#####
# This handles the loading of my automations
# Each automation is in separate YAML file
# https://www.home-assistant.io/docs/automation/
#####

automation yaml: !include_dir_list ../automations
