alias: Visitor's Bathroom - Automatic lights based on motion and illuminance
description: Currently set at 5 minutes and 220 lux
trigger:
  - platform: state
    entity_id: light.visitor_s_bathroom_child_switch_lower_button_lamp
    to: 'on'
    id: lower_light
  - platform: state
    entity_id: light.visitor_s_bathroom_child_switch_middle_button_main_lamp
    to: 'on'
    id: upper_light
  - platform: state
    entity_id: binary_sensor.motion_visitor_s_bathroom_motion
    id: motion_stopped
    to: 'off'
  - platform: event
    event_type: timer.finished
    id: timer_finished
    event_data:
      entity_id: timer.visitors_bathroom
  - platform: state
    entity_id: binary_sensor.motion_visitor_s_bathroom_motion
    id: motion_detected
    to: 'on'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: lower_light
        sequence:
          - service: timer.start
            target:
              entity_id: timer.visitors_bathroom
      - conditions:
          - condition: trigger
            id: upper_light
        sequence:
          - service: timer.start
            target:
              entity_id: timer.visitors_bathroom
      - conditions:
          - condition: trigger
            id: motion_stopped
        sequence:
          - service: timer.start
            target:
              entity_id: timer.visitors_bathroom
      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.visitor_s_bathroom_child_switch_lower_button_lamp
          - service: light.turn_off
            target:
              entity_id: light.visitor_s_bathroom_child_switch_middle_button_main_lamp
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: numeric_state
            entity_id: sensor.motion_visitor_s_bathroom_illuminance
            below: '220'
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.visitors_bathroom
          - service: light.turn_on
            target:
              entity_id: light.visitor_s_bathroom_child_switch_lower_button_lamp
          - service: light.turn_on
            target:
              entity_id: light.visitor_s_bathroom_child_switch_middle_button_main_lamp
    default: []
mode: single
