
homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named integrations     # package setup/config split
script: !include scripts.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

#This part is for Alexa actionable notifications
#input_text:
#  alexa_actionable_notification:
#    name: Alexa Actionable Notification Holder
#    max: 255
#    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'