#####
# Enable Zigbee2MQTT join after switch is on
# 
#####

alias: (YAML) Zigbee Join Enabled
id: 21f56711-bb88-4d8e-9aca-4ddfbe11f40f

trigger:
  platform: state
  entity_id: switch.zigbee2mqtt_join
  to: "on"

action:
  service: timer.start
  entity_id: timer.zigbee_permit_join
  data_template:
    duration: "{{ '00:0%i:00' % (states('input_number.zigbee2mqtt_join_minutes') | int ) }}"