#####
# Get notified when new Zigbee device joins
# 
#####

alias: (YAML) Zigbee Device Joined Notification
id: 8f6e1c5d-2000-43b4-a4a9-a90526f96544

trigger:
  platform: mqtt
  topic: 'zigbee2mqtt/bridge/log'

condition: '{{trigger.payload_json.type == "pairing" and trigger.payload_json.message == "interview_successful"}}'
#  condition: template
#  value_template: '{{trigger.payload_json.type == "pairing" and trigger.payload_json.message == "interview_successful"}}'

action:
  - service: persistent_notification.create
    data_template:
      title: Device joined the Zigbee2MQTT network
      message: "Name: {{trigger.payload_json.meta.friendly_name}},
                Vendor: {{trigger.payload_json.meta.vendor}},
                Description: {{trigger.payload_json.meta.description}}"