#####
# Disable Zigbee2MQTT join after timer ends
# 
#####

alias: (YAML) Zigbee Join Disabled
id: 3a93ca68-0417-40fa-9b12-e5238ed4a398

trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  - platform: state
    entity_id: switch.zigbee2mqtt_main_join
    to: "off"

action:
  - service: timer.cancel
    data:
      entity_id: timer.zigbee_permit_join
  - service: switch.turn_off
    entity_id: switch.zigbee2mqtt_join