id: 81151e45-2151-42c0-bef1-47cbe33943c7
alias: (YAML) Dressing Room - Automatic lights based on motion and illuminance
description: >-
  Currently set at 5 minutes and 200 lux.  Updated version that keeps off at
  night
trigger:
  - platform: state
    entity_id: switch.engelbert_s_dressing_room_top
    to: 'on'
    id: upper_light
  - platform: state
    entity_id: binary_sensor.motion_engelbert_s_dressing_room_occupancy
    id: motion_stopped
    to: 'off'
  - platform: event
    event_type: timer.finished
    id: timer_finished
    event_data:
      entity_id: timer.dressing_room_motion
  - platform: state
    entity_id: binary_sensor.motion_engelbert_s_dressing_room_occupancy
    id: motion_detected
    to: 'on'
  - platform: state
    entity_id: binary_sensor.contact_engelbert_s_dressing_room_contact
    id: door_open
    to: 'on'
  - platform: state
    entity_id: binary_sensor.contact_engelbert_s_dressing_room_contact
    id: door_closed
    to: 'off'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: upper_light
        sequence:
          - service: timer.start
            target:
              entity_id:
                - timer.dressing_room_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: motion_stopped
        sequence:
          - service: timer.start
            target:
              entity_id:
                - timer.dressing_room_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.engelbert_s_dressing_room_top
      - conditions:
          - condition: trigger
            id: door_open
          - condition: state
            entity_id: input_boolean.night_mode
            state: 'on'
        sequence:
          - service: switch.turn_off
      - conditions:
          - condition: trigger
            id: door_open
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.engelbert_s_dressing_room_top
      - conditions:
          - condition: trigger
            id: door_closed
        sequence:
          - service: timer.start
            target:
              entity_id:
                - timer.dressing_room_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: state
            entity_id: input_boolean.night_mode
            state: 'on'
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.dressing_room_motion
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: numeric_state
            entity_id: sensor.motion_engelbert_s_dressing_room_illuminance_lux
            below: '200'
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.dressing_room_motion
          - service: switch.turn_on
            target:
              entity_id: switch.engelbert_s_dressing_room_top
    default: []
mode: single