id: d7c74d63-b9fe-40b9-b83d-3a37425fb2cd
alias: (YAML) Girls Bathroom - Automatic lights based on motion and illuminance
description: Currently set at 10 minutes and 200 lux
trigger:
  - platform: state
    entity_id: switch.girls_bathroom_gabriela_s_side_bottom
    to: 'on'
    id: lower_light
  - platform: state
    entity_id: switch.girls_bathroom_gabriela_s_side_top
    to: 'on'
    id: upper_light
  - platform: state
    entity_id: binary_sensor.motion_girls_bathroom_occupancy
    id: motion_stopped
    to: 'off'
  - platform: event
    event_type: timer.finished
    id: timer_finished
    event_data:
      entity_id: timer.girls_girls_bathroom_motion
  - platform: state
    entity_id: binary_sensor.motion_girls_bathroom_occupancy
    id: motion_detected
    to: 'on'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: lower_light
        sequence:
          - service: timer.start
            target:
              entity_id: timer.girls_bathroom_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: upper_light
        sequence:
          - service: timer.start
            target:
              entity_id: timer.girls_bathroom_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: motion_stopped
        sequence:
          - service: timer.start
            target:
              entity_id: timer.girls_bathroom_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - service: light.turn_off
            target:
              entity_id:
                - light.girls_bathroom_lights
      - conditions:
          - condition: trigger
            id: motion_detected
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.girls_bathroom_motion
          - service: light.turn_on
            target:
              entity_id: light.girls_bathroom_lights
    default: []
mode: single