id: 85e48086-872c-424d-97e4-5e002cf3c697
alias: (YAML) Stairs - Lights - Based on motion and illuminance
description: Currently set for 1 minute and 200 lumens
trigger:
  - platform: state
    entity_id: binary_sensor.motion_top_of_stairs_occupancy
    id: motion_top
    to: 'on'
  - platform: state
    entity_id: binary_sensor.motion_top_of_stairs_occupancy
    id: motion_stopped_top
    to: 'off'
  - platform: state
    entity_id: binary_sensor.motion_stairs_bottom_occupancy
    id: motion_down
    to: 'on'
  - platform: state
    entity_id: binary_sensor.motion_stairs_bottom_occupancy
    id: motion_stopped_down
    to: 'off'
  - platform: event
    event_type: timer.finished
    id: timer_stopped
    event_data:
      entity_id: timer.stairs
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_top
          - condition: numeric_state
            entity_id: sensor.motion_top_of_stairs_illuminance_lux
            below: '200'
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.stairs
      - conditions:
          - condition: trigger
            id: motion_stopped_top
        sequence:
          - service: timer.start
            data:
              duration: '0'
            target:
              entity_id: timer.stairs
      - conditions:
          - condition: trigger
            id: motion_down
          - condition: numeric_state
            entity_id: sensor.motion_stairs_bottom_illuminance_lux
            below: '200'
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.stairs
      - conditions:
          - condition: trigger
            id: motion_stopped_down
        sequence:
          - service: timer.start
            data:
              duration: '0'
            target:
              entity_id: timer.stairs
      - conditions:
          - condition: trigger
            id: timer_stopped
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.stairs
    default: []
mode: single