id: 23fea06a-1166-47ae-9a3f-f02e51ad0b96
alias: (YAML) Yini's Dressing Room - Automatic lights based on motion and illuminance
description: Currently set at 1 minutes and 200 lux
trigger:
  - platform: state
    entity_id: switch.yini_s_dressing_room_bottom
    to: 'on'
    id: lower_light
  - platform: state
    entity_id: switch.yini_s_dressing_room_top
    to: 'on'
    id: upper_light
  - platform: state
    entity_id: binary_sensor.motion_yini_s_dressing_room_occupancy
    id: motion_stopped
    to: 'off'
  - platform: event
    event_type: timer.finished
    id: timer_finished
    event_data:
      entity_id: timer.yini_s_dressing_room_motion
  - platform: state
    entity_id: binary_sensor.motion_yini_s_dressing_room_occupancy
    id: motion_detected
    to: 'on'
  - platform: state
    entity_id: binary_sensor.contact_yini_s_dressing_room_contact
    id: door_open
    to: 'on'
  - platform: state
    entity_id: binary_sensor.contact_yini_s_dressing_room_contact
    id: door_closed
    to: 'off'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: lower_light
        sequence:
          - service: timer.start
            target:
              entity_id: timer.yini_s_dressing_room_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: upper_light
        sequence:
          - service: timer.start
            target:
              entity_id: timer.yini_s_dressing_room_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: motion_stopped
        sequence:
          - service: timer.start
            target:
              entity_id: timer.yini_s_dressing_room_motion
            data:
              duration: '0'
      - conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - service: light.turn_off
            target:
              entity_id:
                - light.yini_s_dressing_room_lights
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: numeric_state
            entity_id: sensor.motion_yini_s_dressing_room_illuminance_lux
            below: '200'
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.yini_s_dressing_room_motion
          - service: light.turn_on
            target:
              entity_id: light.yini_s_dressing_room_lights
      - conditions:
          - condition: trigger
            id: door_open
          - condition: numeric_state
            entity_id: sensor.motion_yini_s_dressing_room_illuminance_lux
            below: '200'
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.yini_s_dressing_room_motion
          - service: light.turn_on
            target:
              entity_id: light.yini_s_dressing_room_lights
      - conditions:
          - condition: trigger
            id: door_closed
        sequence:
          - service: timer.start
            target:
              entity_id: timer.yini_s_dressing_room_motion
            data:
              duration: '0'
    default: []
mode: single