id: fa986942-e8a9-4f1c-a86b-71ffc0d390f8
alias: (YAML) Master Bedroom - Shutter open/close
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.contact_balcony_door_contact
    to: "on"
    id: open
  - platform: state
    entity_id: binary_sensor.contact_balcony_door_contact
    to: "off"
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
    id: close
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: open
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.virtual_second_shutter_up
      - conditions:
          - condition: trigger
            id: close
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.virtual_second_shutter_down
    default: []
mode: single
